name: Testar execução do programa

on:
  push:
    branches: [ pdf-help_2 ]

jobs:
  executar:
    runs-on: ubuntu-latest

    env:
      MODO_TESTE: 1  # ativa o modo de frase fixa

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Configurar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependências
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Executar o programa
      run: |
        python main.py
